services:
  - type: web
    name: review-platform
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application --workers=$WEB_CONCURRENCY --threads=4 --worker-tmp-dir=/dev/shm"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings.production
      - key: ALLOWED_HOSTS
        value: .onrender.com,127.0.0.1,localhost
    autoDeploy: true
