# Generated by Django 5.2.8 on 2026-01-01 00:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Main content of the blog post. Supports images, highlighting, and formatting.'),
        ),
    ]
