# Generated by Django 5.2.8 on 2025-11-29 11:46

import django.core.validators
import django.db.models.deletion
import review.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('prompt', models.TextField()),
                ('choices', models.JSONField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('mc', 'Multiple Choice'), ('tf', 'True / False')], default='text', max_length=10)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_premium', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('topic', 'order'),
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ('key',),
                'indexes': [models.Index(fields=['key'], name='review_feat_key_bb9186_idx'), models.Index(fields=['enabled'], name='review_feat_enabled_7b624d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_premium', models.BooleanField(db_index=True, default=True)),
                ('exam_file', models.FileField(blank=True, null=True, upload_to='mock_exams/%Y/%m/%d/', validators=[review.models.validate_file_max_size, review.models.validate_file_allowed_extensions])),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questions', models.ManyToManyField(blank=True, related_name='mock_exams', to='review.question')),
            ],
            options={
                'verbose_name': 'Mock Exam',
                'verbose_name_plural': 'Mock Exams',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entry', to='review.question')),
            ],
            options={
                'verbose_name': 'Daily Question',
                'verbose_name_plural': 'Daily Questions',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ReviewFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='review_files/%Y/%m/%d/', validators=[review.models.validate_file_max_size, review.models.validate_file_allowed_extensions])),
                ('is_premium', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_review_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review File',
                'verbose_name_plural': 'Review Files',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ('order', 'title'),
                'indexes': [models.Index(fields=['slug'], name='review_subj_slug_c5feca_idx'), models.Index(fields=['order'], name='review_subj_order_55e5b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=140)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='review.subject')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ('subject', 'order', 'title'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='review.topic'),
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('plan', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Access',
                'verbose_name_plural': 'User Accesses',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='review.question')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='review.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
                'ordering': ('-last_attempted_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('state', models.CharField(choices=[('running', 'Running'), ('finished', 'Finished'), ('timed_out', 'Timed Out')], db_index=True, default='running', max_length=20)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='review.mockexam')),
            ],
            options={
                'verbose_name': 'Exam Session',
                'verbose_name_plural': 'Exam Sessions',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['user', 'mock_exam'], name='review_exam_user_id_b6fdb7_idx'), models.Index(fields=['state'], name='review_exam_state_2c227b_idx'), models.Index(fields=['expires_at'], name='review_exam_expires_fddcca_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='payments/%Y/%m/%d/', validators=[review.models.validate_file_max_size, review.models.validate_file_allowed_extensions, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='review_paym_user_id_c06c98_idx'), models.Index(fields=['provider_reference'], name='review_paym_provide_3cb9f7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['is_premium'], name='review_mock_is_prem_c99b65_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['duration_minutes'], name='review_mock_duratio_62fc65_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyquestion',
            index=models.Index(fields=['date'], name='review_dail_date_fd0d26_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyquestion',
            index=models.Index(fields=['is_active'], name='review_dail_is_acti_1a0433_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewfile',
            index=models.Index(fields=['is_premium'], name='review_revi_is_prem_009d13_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewfile',
            index=models.Index(fields=['uploaded_by'], name='review_revi_uploade_fca90c_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['subject', 'order'], name='review_topi_subject_9ebbbf_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_active'], name='review_topi_is_acti_7fb8bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'slug')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'order'], name='review_ques_topic_i_2d0c03_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='review_ques_is_acti_156e14_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_premium'], name='review_ques_is_prem_8350e7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='review_ques_created_8e8222_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccess',
            index=models.Index(fields=['user', 'is_active'], name='review_user_user_id_fa3ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccess',
            index=models.Index(fields=['source_reference'], name='review_user_source__2ce9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccess',
            index=models.Index(fields=['expires_at'], name='review_user_expires_9f1805_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useraccess',
            unique_together={('user', 'source_reference')},
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['user'], name='review_user_user_id_a05969_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['question'], name='review_user_questio_7999e8_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['topic'], name='review_user_topic_i_fe45ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranalytics',
            unique_together={('user', 'question')},
        ),
    ]
