# Generated by Django 5.2.8 on 2025-12-15 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, only allowed users can see this subject.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, only allowed users can see this topic.'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_private'], name='review_subj_is_priv_063288_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_private'], name='review_topi_is_priv_02b15e_idx'),
        ),
    ]
