# Generated by Django 5.2.8 on 2025-12-15 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_subject_allowed_users_subject_is_private_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, only allowed users can see this exam.'),
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['is_private'], name='review_mock_is_priv_9713ee_idx'),
        ),
    ]
