# Generated by Django 5.2.8 on 2025-12-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_mockexam_allowed_users_mockexam_is_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(help_text='Test change', max_length=255),
        ),
    ]
