# Generated by Django 5.2.8 on 2025-12-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_subject_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='folder',
            field=models.CharField(blank=True, db_index=True, default='General', help_text='Folder name to group topics under a subject', max_length=255),
        ),
    ]
