# Generated by Django 5.2.8 on 2025-12-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_subject_title'),
        ('review', '0006_folder_model_migration'),
    ]

    operations = [
    ]
