# Generated by Django 5.2.8 on 2025-12-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_merge_20251217_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('subject', 'folder_ref__order', 'folder_ref__title', 'order', 'title'), 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
