# Generated by Django 5.2.8 on 2025-12-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_topic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for the landing page.', null=True, upload_to='subjects/'),
        ),
    ]
